### ISSUE TITLE
Open VSIX doesn't load all settings

### ISSUE THREAD

**Issue by ngzero** [AlessandroDelSole/CodeSnippetStudio#10]
Snippet Folder Name and License are not loaded correctly if open vsix button is used.
Snippet Folder Name contains always "My custom snippets".
License is always the file name and not the path that was set before.
![devenv_2016-05-19_13-34-24](https://cloud.githubusercontent.com/assets/3295801/15392289/73a7d340-1dc6-11e6-8d46-0f741d4d14a5.png)

**Comment by AlessandroDelSole** [comment]
Hi, here's the explanation:
1. The snippet folder name is not stored inside the package's metadata. Rather this is a physical folder inside the .vsix package. Because you might have dozens extensions, and thus dozens folders, inside a .vsix package, it's not easy to detect the proper folder. However, I'll put this into the todo list.
2. A .vsix is nothing but a .zip archive. The License file is stored in the root of this archive; it is not stored inside a subfolder, nor in a local path. When packaged, a .vsix doesn't care where the license file was picked from and therefore it doesn't store the original path anywhere. What Studio can do at this point is detecting the license file in the root, showing its name. It's impossible to restore the local path where the file was picked from.
